name: Build with CMake

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.6.0

jobs:
  build:
    strategy:
      matrix:
        with-qt: [true, false]
    name: ${{ matrix.with-qt && 'with' || 'without' }} Qt
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Install Qt
        if: matrix.with-qt
        uses: jurplel/install-qt-action@v3.3.0
        with:
          cache: true
          cache-key-prefix: QtCache-${{ env.QT_VERSION }}
          version: ${{ env.QT_VERSION }}

      - name: Configure CMake
        run: >
          cmake 
          -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DWINTOASTLIB_BUILD_EXAMPLES=On
          -DWINTOASTLIB_QT_ENABLED=${{ matrix.with-qt && 'On' || 'Off' }}

      - name: Build
        working-directory: build
        run: ninja all
